---
- name: Install Docker + cAdvisor + Node Exporter
  hosts: server
  become: yes
  vars_files:
    - vars.yml
  tasks:
    # Install Docker
    - name: Install dependencies for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-docker
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.shell: |
        mkdir -p /etc/apt/keyrings/
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Install Docker Components
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    # Install Node Exporter
    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz

    - name: Unarchive Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Node Exporter
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        remote_src: yes

    - name: Create Node Exporter systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Prometheus Node Exporter
          After=network.target

          [Service]
          User=nobody
          Group=nogroup
          Type=simple
          ExecStart=/usr/local/bin/node_exporter --web.listen-address=:{{ node_exporter_port }}

          [Install]
          WantedBy=multi-user.target

    - name: Start Node Exporter
      systemd:
        name: node_exporter
        state: started
        enabled: yes

    # Install cAdvisor
    - name: Start cAdvisor Container
      docker_container:
        name: cadvisor
        image: "{{ cadvisor_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ cadvisor_port }}:8080"
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:ro
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        privileged: yes

- name: Install Grafana + Prometheus
  hosts: grafana_server
  become: yes
  vars_files:
    - vars.yml
  tasks:
    # Install Prometheus
    - name: Create Prometheus User
      user:
        name: prometheus
        system: yes
        shell: /bin/false

    - name: Create Prometheus Directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Unarchive Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Copy Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0755'
        remote_src: yes
      loop:
        - prometheus
        - promtool

    - name: Copy Prometheus configure files
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/etc/prometheus/{{ item }}"
        remote_src: yes
      loop:
        - prometheus.yml
        - consoles/
        - console_libraries/

    - name: Set ownership of prometheus directories
      file:
        path: /etc/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        recurse: yes

    - name: Create prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/ \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries \
            --web.listen-address=:{{ prometheus_port }}

          [Install]
          WantedBy=multi-user.target

    - name: Copy prometheus configuration from template
      template:
        src: template/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
      notify: restart prometheus

    - name: Start and enable Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes
        daemon_reload: yes

    # Install Grafana
    - name: Add Grafana repository (Without GPG Key)
      apt_repository:
        repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/packages.grafana.com/oss/deb/ stable main"
        filename: grafana
        state: present
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Set Grafana admin password via config
      ini_file:
        path: /etc/grafana/grafana.ini
        section: security
        option: admin_password
        value: "{{ grafana_admin_password }}"
      notify: restart grafana

    - name: Start and enable Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes

  handlers:
    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted

    - name: restart grafana
      systemd:
        name: grafana-server
        state: restarted
