events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # 1. Редирект с HTTP (80) на HTTPS (443)
    server {
        listen 80;
        server_name testingsiten3p.online www.testingsiten3p.online;

        return 301 https://$host$request_uri;
    }

    # 2. Основной сервер с SSL (443)
    server {
        listen 443 ssl;
        server_name testingsiten3p.online www.testingsiten3p.online;

        # Пути к сертификатам Let's Encrypt
        ssl_certificate     /etc/letsencrypt/live/testingsiten3p.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/testingsiten3p.online/privkey.pem;

        # Безопасные протоколы и шифры
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        root /usr/share/nginx/html;

        # Указываем Nginx использовать именно site.html в качестве главной страницы
        index site.html;

        location / {
            try_files $uri $uri/ @backend;
        }

        location @backend {
            proxy_pass http://history_site:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
